In [2]:
!pip install pulp

Requirement already satisfied: pulp in c:\users\thanh\anaconda3\lib\site-packages (2.9.0)

In [3]:
from pulp import *

In [4]:
## create the model
model = LpProblem('Pillow', LpMaximize)

## decision variable 
x1 = LpVariable(name = 'Feather used', lowBound = 0, upBound = None, cat = 'Integer')
x2 = LpVariable(name = 'Cotton used', lowBound = 0, upBound = None, cat = 'Integer')

## objective function
model += x1 * 25 + x2 * 35

## contraints
model += x1 * 0.3 + x2 * 0.5 <= 20
model += x1 * 0.5 + x2 * 0.5 <= 35

## solve
print(f'''Status of the model: {model.solve()}''')

## objective value
print(f'''Objective function outcome: {value(model.objective)}''')

## variable
print(f'''x1 is {x1.varValue}
x2 is {x2.varValue}''')

Status of the model: 1
Objective function outcome: 1660.0
x1 is 65.0
x2 is 1.0

In [5]:
## create the model
model = LpProblem('Pillow', LpMaximize)

## decision variable 
x1 = LpVariable(name = 'Feather used', lowBound = 0, upBound = None, cat = 'Integer')
x2 = LpVariable(name = 'Cotton used', lowBound = 0, upBound = None, cat = 'Integer')
x3 = LpVariable(name = 'Silk used', lowBound = 0, upBound = None, cat = 'Integer')

## objective function
model += 33*x1 + 40*x2 + 34*x3

## contraints
model += 0.4*x1 + 0.7*x2 + 0.4*x3 <= 40
model += 0.2*x1 + 0.5*x2 + 0.6*x3 <= 40
model += 0.3*x1 + 0.3*x2 + 0.2*x3 <= 40

## solve
print(f'''Status of the model: {model.solve()}''')

## objective value
print(f'''Objective function outcome: {value(model.objective)}''')

## variable
print(f'''
x1 is {x1.varValue}
x2 is {x2.varValue}
x3 is {x3.varValue}''')

Status of the model: 1
Objective function outcome: 3350.0

x1 is 50.0
x2 is 0.0
x3 is 50.0

In [6]:
## parameter
cost = [
[[50, 80, 50],
[60, 90, 60],
[70, 90, 70]],
[[80, 50, 80],
[90, 60, 90],
[90, 70, 90]]
]

demand = [
[50, 120, 30],
[80, 80, 60],
[200, 40, 175]
]

supply = [500, 500]

I = range(2)
J = range(3)
K = range(3)

## create the model
model = LpProblem('Furniture', LpMinimize)

## decision variable

x = LpVariable.dicts("# shipped from factory i of product j to customer k", (I, J, K), 
                     lowBound = 0, upBound = None, cat = 'Integer')

## objective function
model += sum(x[i][j][k] * cost[i][j][k]  for i in I for j in J for k in K)

## contraints
for j in J:
    for k in K:
        model += sum(x[i][j][k] for i in I) >= demand[j][k]
for i in I:
        model += sum(x[i][j][k] for j in J for k in K) <= supply[i]

## solve the model
print(f'''Status of the model: {model.solve()}''')

## objective value
print(f'''Objective function outcome: {value(model.objective)}''')

## print the value
for i in I:
    for j in J:
        for k in K:
            print(f'''{x[i][j][k]} : {x[i][j][k].varValue}''')

Status of the model: 1
Objective function outcome: 54150.0
#_shipped_from_factory_i_of_product_j_to_customer_k_0_0_0 : 50.0
#_shipped_from_factory_i_of_product_j_to_customer_k_0_0_1 : 0.0
#_shipped_from_factory_i_of_product_j_to_customer_k_0_0_2 : 30.0
#_shipped_from_factory_i_of_product_j_to_customer_k_0_1_0 : 80.0
#_shipped_from_factory_i_of_product_j_to_customer_k_0_1_1 : 0.0
#_shipped_from_factory_i_of_product_j_to_customer_k_0_1_2 : 60.0
#_shipped_from_factory_i_of_product_j_to_customer_k_0_2_0 : 105.0
#_shipped_from_factory_i_of_product_j_to_customer_k_0_2_1 : 0.0
#_shipped_from_factory_i_of_product_j_to_customer_k_0_2_2 : 175.0
#_shipped_from_factory_i_of_product_j_to_customer_k_1_0_0 : 0.0
#_shipped_from_factory_i_of_product_j_to_customer_k_1_0_1 : 120.0
#_shipped_from_factory_i_of_product_j_to_customer_k_1_0_2 : 0.0
#_shipped_from_factory_i_of_product_j_to_customer_k_1_1_0 : 0.0
#_shipped_from_factory_i_of_product_j_to_customer_k_1_1_1 : 80.0
#_shipped_from_factory_i_of_product_j_to_customer_k_1_1_2 : 0.0
#_shipped_from_factory_i_of_product_j_to_customer_k_1_2_0 : 95.0
#_shipped_from_factory_i_of_product_j_to_customer_k_1_2_1 : 40.0
#_shipped_from_factory_i_of_product_j_to_customer_k_1_2_2 : 0.0

In [7]:
import pandas as pd

In [8]:
param = pd.read_excel('production_scheduling.xlsx', sheet_name = 'Sheet1')
param

       period  demand  fixed cost  var  storage cost  capacity
0    period 1    3000        2000   40             1      4000
1    period 2    4000        2000   40             1      4000
2    period 3    2500        2000   40             1      4000
3    period 4    4000        2000   40             1      4000
4    period 5    6000        2000   40             1      4000
5    period 6     100        2000   40             1      4000
6    period 7     250        2000   40             1      4000
7    period 8    5000        2000   40             1      4000
8    period 9    6000        2000   40             1      4000
9   period 10     800        2000   40             1      4000
10  period 11     900        2000   40             1      4000
11  period 12    1200        2000   40             1      4000

In [9]:
param['t'] = range(1,13)
param = param.set_index(param['t'])
param

       period  demand  fixed cost  var  storage cost  capacity   t
t
1    period 1    3000        2000   40             1      4000   1
2    period 2    4000        2000   40             1      4000   2
3    period 3    2500        2000   40             1      4000   3
4    period 4    4000        2000   40             1      4000   4
5    period 5    6000        2000   40             1      4000   5
6    period 6     100        2000   40             1      4000   6
7    period 7     250        2000   40             1      4000   7
8    period 8    5000        2000   40             1      4000   8
9    period 9    6000        2000   40             1      4000   9
10  period 10     800        2000   40             1      4000  10
11  period 11     900        2000   40             1      4000  11
12  period 12    1200        2000   40             1      4000  12

In [10]:
# decision variable
inventory = LpVariable.dicts('inv', indices = list(range(1,13)), lowBound = 0, upBound = None, cat = 'Integer')
inventory[0] = 200

production = LpVariable.dicts('prod', indices = list(range(1,13)), lowBound = 0, upBound = None, cat = 'Integer')

binary = LpVariable.dicts('bin', indices = list(range(1,13)), lowBound = 0, upBound = None, cat = 'Binary')

time_period = list(range(1,13))

# create model
model = LpProblem('production_scheduling', LpMinimize)

# objective function
model += lpSum([binary[t] * param['fixed cost'][t] + production[t] * param['var'][t] + inventory[t] * param['storage cost'][t] for t in time_period])

# constraint
for t in time_period:
    model += production[t] - inventory[t] + inventory[t-1] >= param['demand'][t]
    model += production[t] <= binary[t] * param['capacity'][t]

# solve
model.solve()

# check result
for i in production:
    print(production[i], production[i].varValue)

value(model.objective)

prod_1 3400.0
prod_2 4000.0
prod_3 4000.0
prod_4 4000.0
prod_5 4000.0
prod_6 0.0
prod_7 3250.0
prod_8 4000.0
prod_9 4000.0
prod_10 1700.0
prod_11 0.0
prod_12 1200.0

1373400.0